INSERT INTO [users] ([uid], [name], [email], [photo]) VALUES ('SMHQmVoraCWlbQVyQoIzAnbaEPF2', 'Mick', 'mick@gmail.com', 'https://firebasestorage.googleapis.com/v0/b/troupe-aba27.appspot.com/o/images%2Fmick-avatar.png?alt=media&token=ccbc55d4-e3a7-4a06-b92e-344c281f9ffd');
INSERT INTO [users] ([uid], [name], [email], [photo]) VALUES ('CrGQDIDJxdb4G8CdBOaktfWYYz52', 'Cammie', 'cammie@gmail.com', 'https://firebasestorage.googleapis.com/v0/b/troupe-aba27.appspot.com/o/images%2Fcammie-avatar.png?alt=media&token=1bdefdaf-5bc4-42ce-a5c9-887209983f2a');
INSERT INTO [users] ([uid], [name], [email], [photo]) VALUES ('8LfEFNLoZ1MYBRKHwW8Kx39ZzjU2', 'Bill', 'bill@gmail.com', 'https://media-exp1.licdn.com/dms/image/C4E03AQEbzD_wZVuEZA/profile-displayphoto-shrink_800_800/0/1516821711800?e=2147483647&v=beta&t=baaZNEmzBEStC6k4iOKinAlzlJ4Jskv6aJ4wM3XhFNs');
INSERT INTO [users] ([uid], [name], [email], [photo]) VALUES ('CTmWnNfwyzMWOIhalx1Hy8Zxwmi1', 'Ethan', 'ethan@gmail.com', 'https://firebasestorage.googleapis.com/v0/b/troupe-aba27.appspot.com/o/images%2Fethan-avatar.png?alt=media&token=50857725-3e15-44ff-a7ba-4d29a3e235a4');
INSERT INTO [users] ([uid], [name], [email], [photo]) VALUES ('n2FxrJj0uabHdQYeU4IrF3dBQyk1', 'Scott', 'scott@gmail.com', 'https://firebasestorage.googleapis.com/v0/b/troupe-aba27.appspot.com/o/images%2Fscott-avatar.png?alt=media&token=f9874652-89f0-496d-9548-6e31a31e86cd');
INSERT INTO [users] ([uid], [name], [email], [photo]) VALUES ('Qkl8MSnKkcXslwFx26zuYN4111I3', 'Emma', 'emma@gmail.com', 'https://firebasestorage.googleapis.com/v0/b/troupe-aba27.appspot.com/o/images%2Femma-avatar.png?alt=media&token=19b21aea-6aab-4f9e-83bc-97e28ea2b1fe');
INSERT INTO [users] ([uid], [name], [email], [photo]) VALUES ('T1tSKtnfHNdjuKqR5yryS4cnAa22', 'Allison', 'allison@gmail.com', 'https://firebasestorage.googleapis.com/v0/b/troupe-aba27.appspot.com/o/images%2Fallison-avatar.png?alt=media&token=73d1a18a-bcfd-42d3-bc05-5ba721f18ba6');
INSERT INTO [users] ([uid], [name], [email], [photo]) VALUES ('9kwa5LgGZ6WyVaH30fb2LxMz87f2', 'Brooks', 'brooks@gmail.com', 'https://firebasestorage.googleapis.com/v0/b/troupe-aba27.appspot.com/o/images%2Fbrooks-alford_orig.png?alt=media&token=4d81a635-e262-41a6-9630-6ddab953632e');
INSERT INTO [users] ([uid], [name], [email], [photo]) VALUES ('jTCozQTq2RWNYSLrCIGVhoXxLRP2', 'Edd', 'edd@gmail.com', 'https://firebasestorage.googleapis.com/v0/b/troupe-aba27.appspot.com/o/images%2Fedd-avatar.png?alt=media&token=e7c82e7d-799e-4642-8f68-92fd0830faf2');
INSERT INTO [users] ([uid], [name], [email], [photo]) VALUES ('OTjeuXfODDXRwzapJfevX69rcSK2', 'Isaac', 'isaac@gmail.com', 'https://firebasestorage.googleapis.com/v0/b/troupe-aba27.appspot.com/o/images%2Fisaac-avatar.png?alt=media&token=10d82734-41f7-4e5d-a508-ccb1c9e848dd');
INSERT INTO [users] ([uid], [name], [email], [photo]) VALUES ('6im7ErYGG6hanbQcNZwNS2hOOBm1', 'Kirsten', 'kirsten@gmail.com', 'https://firebasestorage.googleapis.com/v0/b/troupe-aba27.appspot.com/o/images%2Fkirsten-avatar.png?alt=media&token=20e217ef-857e-44bc-affe-9118c780271d');
INSERT INTO [users] ([uid], [name], [email], [photo]) VALUES ('wp2uh3akxHZ6gpZmRNmVrSOstqA3', 'Liz', 'liz@gmail.com', 'https://firebasestorage.googleapis.com/v0/b/troupe-aba27.appspot.com/o/images%2Fliz-avatar.png?alt=media&token=35b9db2c-e00d-4f20-9495-86f4ef78eb66');
INSERT INTO [users] ([uid], [name], [email], [photo]) VALUES ('HoAv41nwXdcnkAVwZmq2OQ1Nh892', 'Max', 'max@gmail.com', 'https://firebasestorage.googleapis.com/v0/b/troupe-aba27.appspot.com/o/images%2Fmax-avatar.png?alt=media&token=7a56c2c9-4f27-4013-a0be-1805c6aed175');
INSERT INTO [users] ([uid], [name], [email], [photo]) VALUES ('0itnYTkTUqNlZtwRoGxrJSNIPMv1', 'Mike', 'mike@gmail.com', 'https://firebasestorage.googleapis.com/v0/b/troupe-aba27.appspot.com/o/images%2Fmike-dapper.png?alt=media&token=577a6317-e1ce-4f6c-86c0-e7fb07073a6b');
INSERT INTO [users] ([uid], [name], [email], [photo]) VALUES ('SJ8QUVD5WcUZKkh4teZK36UiLpu2', 'Susan', 'susan@gmail.com', 'https://firebasestorage.googleapis.com/v0/b/troupe-aba27.appspot.com/o/images%2Fsusan-avatar.png?alt=media&token=f827ccac-17b5-40b2-bc95-992e6d7c9a70');
INSERT INTO [users] ([uid], [name], [email], [photo]) VALUES ('OLqHLYRyK4bw7MvkBORrS0OwJyM2', 'Luke', 'luke@gmail.com', 'https://firebasestorage.googleapis.com/v0/b/troupe-aba27.appspot.com/o/images%2Fluke-avatar.png?alt=media&token=022ef3e4-bb4a-415e-850a-afc6cf58035d');
INSERT INTO [users] ([uid], [name], [email], [photo]) VALUES ('K80j2xWKyqU0UiTasttKPSNkzkJ2', 'Catherine', 'catherine@gmail.com', 'https://firebasestorage.googleapis.com/v0/b/troupe-aba27.appspot.com/o/images%2Fcatherine-avatar.png?alt=media&token=fb6fe6ba-05bb-4b95-9f9b-b5cdad7cbf10');
INSERT INTO [users] ([uid], [name], [email], [photo]) VALUES ('hb7kAEIawWWSvrtRH5X0nn8nqqx1', 'Leigh', 'leigh@gmail.com', 'https://firebasestorage.googleapis.com/v0/b/troupe-aba27.appspot.com/o/images%2Fleigh-avatar.png?alt=media&token=62562de2-1d49-47f4-a0a4-6b04b80ca7ba');
INSERT INTO [users] ([uid], [name], [email], [photo]) VALUES ('vmzZJUSUPNbJKqT0GGTx6rPiqF63', 'Kim', 'kimberley.dalrymple@gmail.com', 'https://firebasestorage.googleapis.com/v0/b/troupe-aba27.appspot.com/o/images%2Fkim-avatar.png?alt=media&token=b02d02c0-602c-473f-ac63-39ed322cf0a0');
INSERT INTO [users] ([uid], [name], [email], [photo]) VALUES ('fnlqKYOSTAWv3QXGa09TmCyUnZk1', 'Danny', 'dannyherrmann91@gmail.com', 'https://firebasestorage.googleapis.com/v0/b/troupe-aba27.appspot.com/o/images%2F138D2BCC-79DB-4A24-8CC5-963C41FDF741.jpeg?alt=media&token=c8758574-d696-4590-a6cf-0fd5a3b8625e');

INSERT INTO troupe (name, logo) VALUES ('Cherry Bomb', 'https://www.nowplayingnashville.com/wp-content/uploads/sites/www.nowplayingnashville.com/images/2021/07/event-featured-Luke-Watson-1626906942-scaled.jpeg');
INSERT INTO troupe (name, logo) VALUES ('The Third Coast Comedy Show', 'https://vboblobprod.blob.core.windows.net/awsvboticketscom/_images/events/31131_event_md_784.jpg');
INSERT INTO troupe (name) VALUES ('Freak Pony');
INSERT INTO troupe (name, logo) VALUES ('Infinity Etc.', 'https://res.cloudinary.com/dostuff-media/image/fetch/https://apps.cdnini.com/service/images/showbills/9b03daac7ddf36673d6f5b9755e548ff_750x600.jpg');

INSERT INTO userTypes (name) VALUES ('Performer');
INSERT INTO userTypes (name) VALUES ('Producer');
INSERT INTO userTypes (name) VALUES ('Coach');
INSERT INTO userTypes (name) VALUES ('Music Director');

INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (1, 1, 1, 2);
INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (2, 1, 0, 1);
INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (2, 2, 0, 1);
INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (3, 2, 0, 1);
INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (3, 4, 1, 2);
INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (4, 1, 1, 3);
INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (5, 2, 1, 3);
INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (2, 4, 0, 1);
INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (6, 1, 0, 1);
INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (7, 2, 1, 1);
INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (8, 2, 0, 1);
INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (9, 1, 0, 1);
INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (10, 1, 0, 1);
INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (11, 1, 0, 1);
INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (12, 1, 0, 1);
INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (13, 1, 0, 1);
INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (14, 1, 0, 1);
INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (15, 1, 0, 1);
INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (16, 2, 0, 1);
INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (17, 2, 0, 1);
INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (18, 2, 0, 1);
INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (19, 1, 0, 1);
INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (4, 2, 0, 1);
INSERT INTO userTroupes (userId, troupeId, isLeader, userTypeId) VALUES (20, 1, 0, 1);
